# don't build tags, it's redundant
if: tag IS blank

git:
  depth: 1
sudo: false
language: node_js
node_js:
 - '8'
 - '6'

env:
  global:
    - NO_UPDATE_NOTIFIER=1

matrix:
  fast_finish: true

cache:
  directories:
  - $HOME/.npm

before_install:
  - npm config set loglevel warn
  - npm install --global npm@latest

install: npm ci

script: npm run ci

notifications:
  slack: lernajs:qHyrojRoqBBu7OhDyX1OMiHQ
