---
git:
  depth: 1
sudo: false
language: node_js
cache:
  directories:
  - node_modules

node_js:
 - "0.12"
 - "4"
 - stable

before_script:
  - git config user.email test@example.com
  - git config user.name "Tester McPerson"
script: npm run ci
