# don't build tags, it's redundant
if: tag IS blank

git:
  depth: 1
sudo: false
language: node_js
node_js:
 - '8'
 - '6'

env:
  global:
    - NO_UPDATE_NOTIFIER=1

matrix:
  fast_finish: true

cache:
  directories:
  - $HOME/.npm
  - node_modules

before_install:
  - npm config set loglevel warn
  - if [[ `node -v` == v6* ]]; then npm i -g npm@latest-5; fi
  - if [[ `npm -v` != `npm v npm dist-tags.latest-5` ]]; then npm i -g npm@latest-5; fi

install: npm i --prefer-offline

before_script:
  - git config --global user.email test@example.com
  - git config --global user.name "Tester McPerson"

script: npm run ci

notifications:
  slack: lernajs:qHyrojRoqBBu7OhDyX1OMiHQ
