# don't build tags, it's redundant
skip_tags: true

clone_depth: 1

environment:
  NO_UPDATE_NOTIFIER: "1"
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "6"

matrix:
  fast_finish: true

cache:
  - '%APPDATA%\npm-cache'
  - node_modules -> package-lock.json

install:
  - ps: Install-Product node $env:nodejs_version
  - npm config set loglevel warn
  - IF %nodejs_version% EQU 6 npm -g install npm@latest-5
  - npm i --prefer-offline

before_test:
  - git config --global user.email test@example.com
  - git config --global user.name "Tester McPerson"

test_script:
  - npm run ci

build: off
